# Generated by Django 5.2.4 on 2025-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('price_min', models.PositiveIntegerField()),
                ('price_max', models.PositiveIntegerField()),
                ('area_min', models.PositiveIntegerField()),
                ('area_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField(help_text='متراژ به متر مربع')),
                ('is_exchange', models.BooleanField(default=False)),
                ('has_key', models.BooleanField(default=False)),
                ('is_advertised', models.BooleanField(default=False)),
                ('is_video_recorded', models.BooleanField(default=False)),
                ('notes_internal', models.TextField(blank=True, help_text='فقط برای دفتر')),
                ('notes_public', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
