# Generated by Django 5.2.4 on 2025-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_bedrooms_property_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
