# Generated by Django 5.2.4 on 2025-07-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('properties', '0004_property_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField(help_text='متراژ به متر مربع')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district')),
            ],
        ),
    ]
