# Generated by Django 5.2.4 on 2025-07-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_pricerange'),
        ('properties', '0006_alter_interestedcustomer_area_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedcustomer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='interestedcustomer',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district'),
        ),
    ]
