# Generated by Django 5.2.4 on 2025-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_interestedcustomer_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='monthly_rent',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
